[[redirects]]
  from = "/api/*"
  to = "https://security-dashboard-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build]
  command = "npm run build"
  publish = "dist"
